title: yuzechen.github.io
email: cyz435641433@gmail..com
description: >- 
  The resume of yuze chen
github_username:  RoarOrSmile
title: The Resume
description: The Computer Developers
show_downloads: true
theme: tactile
plugins:
  - jekyll-feed